### ISSUE TITLE
org.jcodings.exception.CharacterPropertyException: invalid character property name <graphemeclusterbreak=emodifier>

### ISSUE THREAD

**Issue by henrich** [jruby/joni#40]
Recently,  it starts to fail to be tested on Debian unstable environment with below message

```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.05 s - in org.joni.test.TestU
[INFO] Running org.joni.test.TestU8
Pattern: [/\X/] Str: ["
"] Encoding: [UTF-8] Option: [] Syntax: [TEST]
org.jcodings.exception.CharacterPropertyException: invalid character property name <graphemeclusterbreak=emodifier>
        at org.jruby.jcodings/org.jcodings.unicode.UnicodeEncoding.propertyNameToCType(UnicodeEncoding.java:99)
        at org.jruby.joni/org.joni.Parser$GraphemeNames.nameToCtype(Parser.java:954)
        at org.jruby.joni/org.joni.Parser.parseExtendedGraphemeCluster(Parser.java:1082)
        at org.jruby.joni/org.joni.Parser.parseExp(Parser.java:792)
        at org.jruby.joni/org.joni.Parser.parseBranch(Parser.java:1520)
        at org.jruby.joni/org.joni.Parser.parseSubExp(Parser.java:1546)
        at org.jruby.joni/org.joni.Parser.parseRegexp(Parser.java:1579)
        at org.jruby.joni/org.joni.Analyser.compile(Analyser.java:78)
        at org.jruby.joni/org.joni.Regex.<init>(Regex.java:155)
        at org.jruby.joni/org.joni.Regex.<init>(Regex.java:134)
        at org.jruby.joni/org.joni.test.Test.xx(Test.java:113)
        at org.jruby.joni/org.joni.test.Test.x2s(Test.java:223)
        at org.jruby.joni/org.joni.test.Test.x2s(Test.java:218)
        at org.jruby.joni/org.joni.test.TestU8.test(TestU8.java:112)
        at org.jruby.joni/org.joni.test.Test.testRegexp(Test.java:256)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
SEVERE ERROR: invalid character property name <graphemeclusterbreak=emodifier>
(snip)
```

However, it succeeded once in [Octobar 2018](https://buildd.debian.org/status/fetch.php?pkg=jruby-joni&arch=all&ver=2.1.25-1&stamp=1539992496&raw=0).
Could you give me an advice, please?

**Comment by lopex** [comment]
It will be fixed with next joni release, now joni should depend on jcodings version in it's pom

**Comment by andrewshadura** [comment]
Hi, any news on this?

**Comment by andrewshadura** [comment]
This has been promoted to a [release critical bug in Debian](https://bugs.debian.org/923295); unless we can get it fixed, joni will not be in the coming Debian release :disappointed:

**Comment by lopex** [comment]
Started to work on it, should be released on friday.

**Comment by lopex** [comment]
Fixed in https://github.com/jruby/joni/commit/9e1a7462441e882fa40dd0ec6e373be74caa5b4b, but we'll need to make sure jruby tests work as well.

**Comment by lopex** [comment]
@andrewshadura joni-2.1.26 is released, thanks for the report.

**Comment by henrich** [comment]
@lopex Thanks, uploaded to Debian unstable repository, now.
